version: 0.0
os: linux

files:
  # Copy the entire treeseg folder to EC2
  - source: treeseg/
    destination: /home/ubuntu/treeseg/

hooks:
  BeforeInstall:
    - location: /home/ubuntu/treeseg/scripts/build.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: /home/ubuntu/treeseg/scripts/deploy.sh
      timeout: 300
      runas: ubuntu
