version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - sudo yum install -y gcc gcc-c++ make cmake3
      - sudo alternatives --install /usr/bin/cmake cmake /usr/bin/cmake3 1
  pre_build:
    commands:
      - echo "Starting build..."
  build:
    commands:
      - echo "Running build script"
      - ./treeseg/scripts/build.sh
  post_build:
    commands:
      - echo "Build finished, artifacts ready"

artifacts:
  files:
    - treeseg/deploy/**/*