version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - apt-get update
      - apt-get install -y build-essential cmake python3-dev
      - apt-get install -y libpcl-dev libarmadillo-dev libxlsxwriter-dev
  pre_build:
    commands:
      - echo "Starting build..."
      - chmod +x ./treeseg/scripts/build.sh
      - echo "Updating Python paths in CMakeLists.txt..."
      - sed -i 's|/Library/Frameworks/Python.framework/Versions/3.11|/usr|g' treeseg/CMakeLists.txt
      - sed -i 's|libpython3.11.dylib|libpython3.*so|g' treeseg/CMakeLists.txt
  build:
    commands:
      - echo "Running build script"
      - ./treeseg/scripts/build.sh
  post_build:
    commands:
      - echo "Build finished, checking output..."
      - ls -laR treeseg/

artifacts:
  files:
    - '**/*'